// Writes .env.development.local so the e2e dev server points at the LOCAL
// Supabase stack — never production. Creds are derived from the *running* local
// stack (`supabase status -o env`) and the API host is asserted local before
// anything is written. Runs before `playwright test` (see the test:e2e script).
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

function readSupabaseEnv() {
  let raw;
  try {
    raw = execFileSync("supabase", ["status", "-o", "env"], { encoding: "utf8" });
  } catch {
    throw new Error(
      "Could not read `supabase status`. Start the local stack first: `supabase start`."
    );
  }
  const env = {};
  for (const line of raw.split("\n")) {
    const idx = line.indexOf("=");
    if (idx <= 0) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    env[key] = value;
  }
  return env;
}

const env = readSupabaseEnv();
const apiUrl = env.API_URL ?? "";
const host = apiUrl ? new URL(apiUrl).hostname : "";
if (!["127.0.0.1", "localhost", "::1"].includes(host)) {
  throw new Error(`Refusing to wire e2e to non-local Supabase host "${host}" (API_URL=${apiUrl}).`);
}
if (!env.ANON_KEY || !env.SERVICE_ROLE_KEY) {
  throw new Error("Local Supabase ANON_KEY / SERVICE_ROLE_KEY missing from `supabase status`.");
}

const contents =
  [
    "# AUTO-GENERATED by tests/e2e/setup-env.mjs — points the dev app at LOCAL Supabase for e2e.",
    "# Gitignored; overrides .env in dev mode (Vite loadEnv). Safe to delete.",
    `SUPABASE_URL="${apiUrl}"`,
    `SUPABASE_DATABASE_URL="${apiUrl}"`,
    `SUPABASE_ANON_KEY="${env.ANON_KEY}"`,
    `SUPABASE_SERVICE_ROLE_KEY="${env.SERVICE_ROLE_KEY}"`,
    'APP_URL="http://localhost:4321"',
    'NETLIFY_SITE_URL="http://localhost:4321"',
    'APP_ENCRYPTION_KEY="e2e-local-encryption-key-not-a-real-secret-000000"',
  ].join("\n") + "\n";

writeFileSync(".env.development.local", contents, "utf8");
console.log(`[e2e] wrote .env.development.local → ${apiUrl}`);
